### ISSUE TITLE
Update readme for install from GitHub

### ISSUE THREAD

**Issue by kyeah** [TalariaSoftware/uswds_components#8]
Hello!

Thank you for maintaining this project. We have some interest in leveraging this library, but I get the following error when attempting to install it:

```
$ bundle add uswds_components
Could not find gem 'uswds_components' in rubygems repository https://rubygems.org/
or installed locally.
```

[Searching on the rubygems site](https://rubygems.org/search?query=uswds) doesn't pull up anything either. Is this gem intended to be distributed through rubygems? Is there another distribution method?

Thank you!

**Comment by ExMember** [comment]
Hello!

First, sorry for the late response. I did not see this issue until today.

Yes, uswds_component has not been published on RubyGems yet. Until it is, you can install it from git by adding this line to your Gemfile:

```ruby
gem 'uswds_component', git: 'https://github.com/TalariaSoftware/uswds_components.git
```

I will update the README to include that information in the future.
